theme:
    features:
        - toc.integrate
extra_css:
    - css/labs.css
markdown_extensions:
    - admonition
    - mdx_math
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
nav:
    - index.md
extra:
    generator: false
plugins:
    - mkdocs-jupyter
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxhelper.js